# -*- coding: utf-8 -*-
"""EDUBOT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwAAntTtKHAikRHrKZrTwbjYYL-KTL0H
"""

# ===============================================
# EduBot: Professional College Information Assistant (PyDatalog + NLP)
# ===============================================

# --- Step 1: Install dependencies ---
!pip install pyDatalog --quiet
!pip install fuzzywuzzy python-Levenshtein --quiet

# --- Step 2: Imports ---
from pyDatalog import pyDatalog
from fuzzywuzzy import fuzz
import re
import random

# --- Step 3: Initialize ---
pyDatalog.clear()

# ===============================================
# KNOWLEDGE BASE — EXTENDED DATASET
# ===============================================

# --- College Info ---
pyDatalog.assert_fact('college', 'ManavRachna College of Engineering', 'Faridabad', 'Top-ranked AI and Tech Institution in India')

# --- Departments ---
departments = [
    ('CSE', 'Computer Science & Engineering – 120 intakes'),
    ('ECE', 'Electronics & Communication Engineering – 90 intakes'),
    ('ME', 'Mechanical Engineering – 60 intakes'),
    ('AI&ML', 'Artificial Intelligence & Machine Learning – 60 intakes'),
    ('EEE', 'Electrical & Electronics Engineering – 60 intakes'),
    ('CIVIL', 'Civil Engineering – 60 intakes'),
    ('IT', 'Information Technology – 90 intakes'),
    ('BIO', 'Biotechnology – 45 intakes'),
]
for d in departments:
    pyDatalog.assert_fact('department', *d)

# --- Courses ---
courses = [
    ('B.Tech CSE', '4 years', 'Focus on AI, Data Science, and Cloud Computing'),
    ('B.Tech ECE', '4 years', 'Advanced Communication Systems and VLSI'),
    ('B.Tech ME', '4 years', 'Manufacturing, Design, and Automation'),
    ('B.Tech AI&ML', '4 years', 'Deep Learning, NLP, Computer Vision'),
    ('B.Tech IT', '4 years', 'Software Engineering and Cybersecurity'),
    ('M.Tech CSE', '2 years', 'Advanced Data Analytics and IoT'),
    ('M.Tech AI', '2 years', 'AI Research, Robotics, and NLP'),
    ('M.Tech VLSI', '2 years', 'Chip Design and Embedded Systems'),
    ('PhD CSE', '5 years', 'Distributed Systems and Quantum Computing'),
    ('PhD AI', '5 years', 'AI Ethics, Generative Models, and AGI Research'),
]
for c in courses:
    pyDatalog.assert_fact('course', *c)

# --- Facilities ---
facilities = [
    ('Library', 'Open 8 AM – 8 PM | 100,000+ books | IEEE, ACM Digital access'),
    ('Hostel', 'Separate hostels for boys and girls | 24×7 Wi-Fi and security'),
    ('Cafeteria', 'Multi-cuisine food court open till 10 PM'),
    ('Sports Complex', 'Cricket, Football, Badminton, Gym & Swimming Pool'),
    ('Auditorium', '800-seater central hall for conferences and fests'),
    ('Innovation Hub', '24×7 open makerspace for startups and robotics'),
]
for f in facilities:
    pyDatalog.assert_fact('facility', *f)

# Add 100 computer labs dynamically
for i in range(1, 101):
    pyDatalog.assert_fact('facility', f'Computer Lab {i}', f'{20 + i} high-end systems | GPU-enabled | Open 9 AM – 7 PM')

# --- Faculty ---
faculty_list = [
    ('Dr. Meena Sharma', 'Dean – AI Department | 15 years research in NLP'),
    ('Dr. Rajesh Verma', 'Professor – CSE | Cloud Computing and Data Mining expert'),
    ('Prof. Neha Kapoor', 'Head – AI & ML | Deep Learning specialist | Ex-Microsoft Research'),
    ('Dr. A.K. Rao', 'Professor – ECE | IoT and Embedded Systems'),
    ('Dr. Jyoti Mishra', 'Associate Professor – Biotechnology | Genetic Engineering'),
]
for f in faculty_list:
    pyDatalog.assert_fact('faculty', *f)

# Add 200 faculty entries dynamically
for i in range(1, 201):
    dept = random.choice(['CSE', 'ECE', 'AI&ML', 'ME', 'EEE', 'IT', 'BIO', 'CIVIL'])
    pyDatalog.assert_fact('faculty', f'Dr. Faculty {i}', f'Assistant Professor – {dept} | Research in AI Topic #{i}')

# --- Research Labs ---
labs = [
    ('AI Drone Lab', 'Autonomous navigation and vision AI'),
    ('Robotics Lab', 'Humanoid robotics and reinforcement learning projects'),
    ('NLP Lab', 'Speech processing and chatbot development'),
    ('Quantum Computing Lab', 'Quantum ML and AI acceleration research'),
    ('Bioinformatics Lab', 'AI-driven genomic analysis'),
]
for l in labs:
    pyDatalog.assert_fact('research', *l)

# Add 50 more labs dynamically
for i in range(1, 51):
    pyDatalog.assert_fact('research', f'AI Innovation Lab {i}', f'Applied AI Research Project #{i} on smart systems')

# --- Events ---
events = [
    ('TechNova', 'National-level AI and Tech Fest every March'),
    ('InnovateX', 'Startup Hackathon with ₹2 Lakh prizes'),
    ('CulturalFest', '3-day music and dance festival every December'),
    ('RoboWars', 'Autonomous Robot Battle Event'),
    ('DataVerse', 'Annual Data Science Summit with Industry Speakers'),
]
for e in events:
    pyDatalog.assert_fact('event', *e)

# Add 100 seminars dynamically
for i in range(1, 101):
    pyDatalog.assert_fact('event', f'Seminar {i}', f'Guest Lecture on AI Innovation Topic #{i}')

# --- Placements ---
placements = [
    ('2021', 'Avg: 6.5 LPA | Highest: 28 LPA @ Google'),
    ('2022', 'Avg: 6.8 LPA | Highest: 32 LPA @ Microsoft'),
    ('2023', 'Avg: 7.5 LPA | Highest: 40 LPA @ Amazon'),
    ('2024', 'Avg: 8.2 LPA | Highest: 45 LPA @ Google'),
    ('2025', 'Avg: 9.0 LPA | Highest: 52 LPA @ OpenAI'),
]
for p in placements:
    pyDatalog.assert_fact('placement', *p)

# ===============================================
# QUERY FUNCTIONS
# ===============================================

def get_category_info(category):
    mapping = {
        'college': 'college(X,Y,Z)',
        'department': 'department(X,Y)',
        'course': 'course(X,Y,Z)',
        'event': 'event(X,Y)',
        'facility': 'facility(X,Y)',
        'faculty': 'faculty(X,Y)',
        'placement': 'placement(X,Y)',
        'research': 'research(X,Y)',
    }
    q = pyDatalog.ask(mapping.get(category, ''))
    return q.answers if q else []

def get_info(category, keyword=None):
    data = get_category_info(category)
    if not data:
        return "No data available."

    if keyword:
        data = [d for d in data if keyword.lower() in str(d).lower()]
        if not data:
            return f"No results found for '{keyword}'."

    response = ""
    for d in data[:20]:  # Limit display for readability
        response += "- " + " | ".join(map(str, d)) + "\n"
    if len(data) > 20:
        response += f"\n...and {len(data) - 20} more entries.\n"
    return response

# ===============================================
# CHATBOT LOGIC
# ===============================================

def interpret_query(user_input):
    keywords = {
        'college': ['college', 'about college', 'about abc'],
        'department': ['department', 'branches', 'streams'],
        'course': ['course', 'program', 'degree'],
        'event': ['event', 'fest', 'seminar', 'hackathon'],
        'facility': ['facility', 'library', 'hostel', 'canteen', 'lab', 'sports', 'auditorium'],
        'faculty': ['faculty', 'teacher', 'professor', 'staff'],
        'placement': ['placement', 'salary', 'package', 'hiring'],
        'research': ['research', 'lab', 'center', 'innovation'],
    }

    for cat, words in keywords.items():
        for w in words:
            if fuzz.partial_ratio(w, user_input) > 80:
                return cat
    return None

def generate_response(category, user_input):
    if not category:
        return "I’m sorry, I couldn’t understand your question. Please rephrase or specify a category."

    keyword = None
    match = re.search(r'\b(20\d{2})\b', user_input)
    if match:
        keyword = match.group(1)

    data = get_info(category, keyword)
    if data.startswith("No"):
        return data

    titles = {
        'college': "COLLEGE OVERVIEW",
        'department': "DEPARTMENTS OFFERED",
        'course': "ACADEMIC PROGRAMS",
        'event': "EVENTS AND SEMINARS",
        'facility': "CAMPUS FACILITIES",
        'faculty': "FACULTY INFORMATION",
        'placement': "PLACEMENT RECORDS",
        'research': "RESEARCH AND INNOVATION LABS",
    }

    return f"{titles[category]}\n{'=' * 40}\n{data}"

# ===============================================
# RUN CHATBOT
# ===============================================

def edubot():
    print("Welcome to EduBot — Your College Information Assistant.")
    print("You can ask questions like:")
    print("  - Show me the AI & ML department")
    print("  - What are placements in 2025?")
    print("  - List all research labs\n")
    print("Type 'exit' to quit.\n")

    while True:
        user = input("You: ").strip().lower()
        if user in ['exit', 'quit']:
            print("EduBot: Goodbye! Have a great day.")
            break

        category = interpret_query(user)
        response = generate_response(category, user)
        print("\n" + response + "\n")

# ===============================================
# START BOT
# ===============================================
edubot()

